### ISSUE TITLE
More detailed tracing

### ISSUE THREAD

**Issue by heqyoufree** [vfsfitvnm/frida-il2cpp-bridge#238] opened 2022-10-19 03:34 UTC
I wanted to looking to a method and tried to find what methods called it or what methods it called.
When tracer is set to filter certain class it wouldn't give the context;

E.g. ClassA.a called ClassB.b. When i trace the ClassB.b i don't know ClassA.a called it.
Also ClassB.b called ClassC.c then i don.t know ClassC.c is called.

**Comment by vfsfitvnm** [comment] 2022-10-19 05:19
Duplicate of #161

**Closed as not planned by vfsfitvnm** 2022-10-19 05:19 UTC
Labels: duplicate
