### ISSUE TITLE
Issues running with Frida Gadget

### ISSUE THREAD

**Issue by ExternalAddress4401** [vfsfitvnm/frida-il2cpp-bridge#299] opened 2023-05-18 02:09 UTC
There's still an issue that occurs with frida gadget. I'm running version 0.8.1 and Android 13.

My script is as follows:

```
import "frida-il2cpp-bridge";
import Logger from "../lib/Logger.js";

Il2Cpp.perform(() => {
  Logger.log(`Inside perform block`);
});
```

Where the Logger method just prints as so

```
    var Log = Java.use("android.util.Log");
    Log.v("script", str);
```

This gives no output.

To get an output from this you must change https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/master/src/il2cpp/module.ts#L48 and remove the `setImmediate` call then call resolve directly.

**Comment by vfsfitvnm** [comment] 2023-05-18 17:09
This one might be a duplicate of #185 or #95.

Would you confirm this is not the case?
https://github.com/vfsfitvnm/frida-il2cpp-bridge/issues/95#issuecomment-1040747383

**Comment by vfsfitvnm** [comment] 2023-06-21 18:24
Closing for inactivity.

**Closed as not planned by vfsfitvnm** 2023-06-21 18:24 UTC
Labels: needs triage
