### ISSUE TITLE
Logging vector fields results in strange values

### ISSUE THREAD

**Issue by Forleyor** [vfsfitvnm/frida-il2cpp-bridge#17] opened 2021-07-17 09:14 UTC
I have been playing with this for a while on a Pixel 2 XL (Android 9) however I tried some of the code in the readme and I am wondering if I am reading or misinterpreting the code somehow?

```js
const Vector2Class = coreModule.classes["UnityEngine.Vector2"];
const vec = Il2Cpp.Object.from(Vector2Class);
vec.methods[".ctor"].invoke(36, 4);

log("X: " + vec.fields.x.value);
log("Y: " + vec.fields.y.value);
```

This results in different values logged everytime such as:

```
X: -8.035985385019588e+22
Y: -2.1116959453495674e+34
```

Any ideas what I am missing?

**Comment by vfsfitvnm** [comment] 2021-07-17 10:13
Uhm, I reproduced this issue, too. This is strange because I'm pretty sure it used to work.
By the way, the problem is the "wrong" number formatting with floating points numbers `System.Single` / `System.Double`.
(I just tested this with `System.Decimal` constructors...).

This is how I build the native function parameter types:
https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/master/src/il2cpp/structs/method.ts#L77
As you can see, I just pass `"pointer"` types, however this leads to incorrect double/float formatting (I'm pretty sure this wasn't an issue few months back).

Fix is coming soon!

**Comment by Forleyor** [comment] 2021-07-17 11:56
Nice! Sounds good!

I have also been reminded to ask you if its possible to select which method we want to invoke if there are multiple overloads

Example::

someFunc(Param1, param2);
SomeFunc(param1, param2, param3, param4);

When trying to invoke the 2 param count version il2cpp-bridge kept reporting something like

[il2cpp] Failed to invoke 4 param method, only 2 params were given.

Didnt see a way to declare which version of the method we want.

Please let me know if this would be better in a separate issue report if you would prefer that.

**Comment by vfsfitvnm** [comment] 2021-07-17 12:06
In case of method overloading, a "_${idx}" is appended to the method name, so:
![Screenshot_20210717_140030](https://user-images.githubusercontent.com/46219656/126036238-061df78d-c4f8-464b-8e0d-89be869f9689.png)
The first `PutBytes` is `PutBytes`, the second one is `PutBytes_1`, the third one `PutBytes_2` and so on.

However I plan to change this behaviour with the next release:
The first one still is `PutBytes`, the second one will be `PutBytes_`, the third one `PutBytes__` and so on.

By the way, I suspect the next release won't come very soon: I also noticed (other than the floats thing) other minor changes were introduced, it will take some time to figure them out, I guess!

**Comment by Forleyor** [comment] 2021-07-17 12:11
Ah I see!

Thanks for the info

No rush on releasing as fast as possible, as long as you are aware of it which now you are thats totally fine. Take your time.

**Comment by vfsfitvnm** [comment] 2021-07-27 18:59
This should be fixed now!

**Closed as completed by vfsfitvnm** 2021-07-27 18:59 UTC
